### ISSUE TITLE
Multiple NFS servers

### ISSUE THREAD

**Issue by arahuja** [hammerlab/stratocumulus#17]
It'd be nice to have a read and write NFS server for example. I want to pull data from an NFS server, but never alter that servers contents and then have a separate one as a workspace for ketrew.

**Comment by smondet** [comment]
The library can already do that, it's just the test-deployment that has only one:
https://github.com/hammerlab/stratocumulus/blob/master/src/test/test_deployment.ml#L48
(it's more of "UI/UX" problem to add that to the test-deployment).

**Comment by hammer** [comment]
If you just want to read data why use an NFS server? Why not use an object store like [Google Cloud Storage](https://cloud.google.com/storage/)?

**Comment by smondet** [comment]
Also if you don't want to write cluster configs in OCaml, the environment variables of Stratotemplate are more expressive, and you can put many NFS mounts:
https://github.com/smondet/stratotemplate/blob/master/configuration.env#L37
