### ISSUE TITLE
Put emacs on the docker image

### ISSUE THREAD

**Issue by hammer** [hammerlab/stratocumulus#53]
For some reason `sudo apt-get install emacs` fails on my `stratocumulus` docker image when following the `stratotemplate` directions. Am I supposed to edit `/hostuff/configuration.env` with `vi` like some heathen?

**Comment by smondet** [comment]
What's the error message?
I've installed stuff on the image many times.

**Comment by hammer** [comment]
```
Err http://archive.ubuntu.com/ubuntu/ wily-security/main libgd3 amd64 2.1.1-4ubuntu0.15.10.1
  404  Not Found [IP: 91.189.88.161 80]
Fetched 63.3 MB in 17s (3595 kB/s)
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/libg/libgd2/libgd3_2.1.1-4ubuntu0.15.10.1_amd64.deb  404  Not Found [IP: 91.189.88.161 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by smondet** [comment]
`sudo apt-get update`?

**Comment by hammer** [comment]
ha that's probably it.

**Comment by hammer** [comment]
Yep that works going to show myself out...

**Comment by smondet** [comment]
the docker image gets built when we push to Ketrew's `master` branch so the apt metadata can get old sometimes
